services:
  # Database 
  postgres-db:
    image: postgres:16
    container_name: thequiz-db_c
    restart: always
    environment:
      - POSTGRES_DB=thQuizDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  # Server
  thequiz-server:
    image: thequiz-server_i
    container_name: thequiz-server_c
    restart: unless-stopped
    depends_on:
      - postgres-db
    build:
      context: ./server
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    networks:
      - shared-network

  # App
  thequiz-app:
    image: thequiz-app_i
    container_name: thequiz-app_c
    depends_on:
      - thequiz-server
    build:
      context: ./the-quiz
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
    - shared-network

networks:
  shared-network:

volumes:
  postgres-db:
